[project]
name = "quantum-fir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "pylatexenc>=2.11",
    "qiskit>=2.5.1",
    "qiskit-aer>=0.17.2",
    "qiskit-algorithms>=0.4.0",
    "scipy>=1.18.0",
    "sounddevice>=0.5.5",
]
